PR#0001: Реализованы паттерны "Команда" и "Цепочка обязанностей"
albrettto/dp-2024-lab05 pull request #1
Opened 2024-11-22 12:24 UTC by albrettto

2024-11-22 15:45 UTC, vladushka2000 commented on handlers/base_order_handler.py
> +        self._next_handler = None
указать тип "IOrderHandler" | None

2024-11-22 15:45 UTC, vladushka2000 commented on handlers/stock_check_handler.py
> +        if inventory.get(item, 0) <= 0:
прям кол-во товара в минус уходит?

2024-11-22 15:47 UTC, vladushka2000 commented on db/database.py
> +prices = {
лучше хранить всю инфу о товаре в одной БД, а то у тебя рассинхрон может быть между двумя словаря - в одном будет товар "Ручка", а в другом его не будет, и все приложение посыпится

2024-11-22 15:48 UTC, vladushka2000 commented on exceptions/payment_processing_error.py
> +    def __init__(self, message: str = None):
message: str | None

2024-11-22 15:49 UTC, vladushka2000 commented on commands/process_order_command.py
> +        self.handler = handler
этим полям не обязательно быть публичными

2024-11-23 09:20 UTC, Rognak commented on commands/process_order_command.py
> +        self.handler = handler
Согласен

2024-11-23 09:22 UTC, Rognak commented on exceptions/delivery_error.py
> +    def __init__(self, message: str = None):
pick: в аннотациях необходимо указать Optional

```python
def __init__(self, message: Optional[str] = None):
```
или если python >=3.11
```python
def __init__(self, message: str | None = None):
```

2024-11-23 09:23 UTC, Rognak commented on exceptions/delivery_error.py
> +    def __init__(self, message: str = None):
Исправить здесь и в других классах

2024-11-23 09:25 UTC, Rognak commented on interfaces/icommand.py
> +        pass
pick: принято писать через NotImplementedError

2024-11-23 09:25 UTC, Rognak requested changes
Необходимо исправить замечания

2024-11-24 13:20 UTC, vladushka2000 commented
хорош. Зачел

2024-11-24 13:20 UTC, vladushka2000 approved these changes

2024-11-25 05:02 UTC, merged